### ISSUE TITLE
Error in installation?

### ISSUE THREAD

**Issue by vizzerra** [sagnikbanerjee15/Finder#15]
Hello. I'm getting this error when trying to run finder--the error occurs with example data as well. Any help would be greatly appreciated.

`Traceback (most recent call last):
  File "/data/selaginella/finder/finder", line 648, in <module>
    main()
  File "/data/selaginella/finder/finder", line 586, in main
    validateCommandLineArguments(options,logger_proxy,logging_mutex)
  File "/data/selaginella/finder/finder", line 235, in validateCommandLineArguments
    cmd+=" --runThreadN "+options.cpu
TypeError: can only concatenate str (not "int") to str`

**Comment by sagnikbanerjee15** [comment]
Hello @vizzerra,

Thank you for checking out `finder`. Are you working with the latest version which is on GitHub? I had modified the code a few days back which should take of this error. Please issue the command `git pull` from under the directory where you have downloaded `finder`. It will update `finder` with the latest changes. Please let me know if this works.

Thank you.

**Comment by vizzerra** [comment]
@sagnikbanerjee15 thank you for your help, but the error still persists (see below). Interestingly, it ran until encountering an error in the metadata file, which I fixed, but the error returned.

May 03 16:47:16 ...... FATAL ERROR, exiting
Traceback (most recent call last):
  File "/data/selaginella/finder/finder", line 668, in <module>
    main()
  File "/data/selaginella/finder/finder", line 629, in main
    orchestrateGeneModelPrediction(options,logger_proxy,logging_mutex)
  File "/data/selaginella/finder/finder", line 413, in orchestrateGeneModelPrediction
    alignReadsAndMergeOutput(options,logger_proxy,logging_mutex)
  File "/data/selaginella/finder/scripts/findGenesFromExpression.py", line 307, in alignReadsAndMergeOutput
    alignReadsWithSTARRound1(options,Run,options.mrna_md[condition][Run]["Ended"],condition,logger_proxy,logging_mutex)
  File "/data/selaginella/finder/scripts/alignReads.py", line 11, in alignReadsWithSTARRound1
    cmd+=" --runThreadN "+options.cpu
TypeError: can only concatenate str (not "int") to str

**Comment by sagnikbanerjee15** [comment]
Hi @vizzerra,

Thank you for your response. I have figured out why you are encountering the error and I have fixed the code. Please issues a `git pull` from your end to get the latest code from GitHub. I am not sure why your system converts the options.cpu into an integer. What system are you running `finder` on?

Thank you.

**Comment by vizzerra** [comment]
That is weird. Finder is running on Linux 4.15 with Ubuntu 18.14.5.

Unfortunately, there is this new error:

  File "/data/selaginella/finder/scripts/fileReadWriteOperations.py", line 232, in readAllTranscriptsFromGTFFileInParallel
    fhr=open(gtf_filename,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/data/selaginella/DATA/annotations/wallacei_1/assemblies_psiclass_modified/combined/combined.gtf'

Is it not outputting the combined.gtf file or something I should fix on my end? Apologies for the headache!

**Comment by sagnikbanerjee15** [comment]
Hello @vizzerra,

Thank you for reporting this error. I think there might be an issue with the transcript generation. Could you please send me your `metadata.csv` file? Also, which organism are you trying to annotate? I do not think there is anything wrong in your end. I just want to make sure that the RNA-Seq samples are provided correctly to `finder`.

Thank you.

**Comment by vizzerra** [comment]
Hi. Here is the metadata.csv

BioProject,SRA Accession,Tissues,Description,Date,Read Length (bp),Ended,RNA Seq,process,Location
Dummy,wallacei,leaf,Illumina,5/3/21,100,SE,1,1,~/DATA/annotations/wallacei/wallacei.scafSeq.fastq

Annotating a selaginella genome, a very small vascular plant.

**Comment by sagnikbanerjee15** [comment]
Hi @vizzerra,

I understand the issue. The location needs to be **only** the directory not the name of the file. The correct content should be:

BioProject,SRA Accession,Tissues,Description,Date,Read Length (bp),Ended,RNA Seq,process,Location
Dummy,wallacei.scafSeq,leaf,Illumina,5/3/21,100,SE,1,1,~/DATA/annotations/wallacei/

`finder` will reconstruct the whole path by merging the location with the SRA Accession (which in your case is a local file). Hence, it will generate the location as `~/DATA/annotations/wallacei/wallacei.scafSeq.fastq`

Hope that helps.

Please let me know if you run into any issues.

Thank you.

**Comment by vizzerra** [comment]
Unfortunately, it spits out the same error

**Comment by sagnikbanerjee15** [comment]
Hi @vizzerra,

Oh, I see. Well, that's a bit disappointing. Could you please send me all the data - the RNA-Seq sample, along with the genome sequence and a protein fasta file (if you have one). I will be able to troubleshoot faster if I have access to the data. You can email those to sagnik@iastate.edu. 

Thank you.

**Comment by vizzerra** [comment]
Email sent. Thank you.
