### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by nick294** [sagnikbanerjee15/Finder#19]
Hi there. I've been having issues running both the example and on my own data, see below:

`~/finder/finder -no_cleanup -mf ~/finder/example/Arabidopsis_thaliana_metadata.csv -n 6 -gdir_star /Volumes/TOSH_EXTERNAL/star_index_without_transcriptome_Arabid -out_dir /Volumes/TOSH_EXTERNAL/Finder_Output1 -g ~/finder/example/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa -p ~/finder/example/uniprot_ARATH.fasta -gdir_olego /Volumes/TOSH_EXTERNAL/olego_index_Arabid -preserve
Traceback (most recent call last):
  File "/Users/nicklister/finder/finder", line 668, in <module>
    main()
  File "/Users/nicklister/finder/finder", line 606, in main
    validateCommandLineArguments(options,logger_proxy,logging_mutex)
  File "/Users/nicklister/finder/finder", line 181, in validateCommandLineArguments
    finder_directory=open(options.temp_dir+"/finding_finder","r").read().split(":")[-1].split()[-1].strip()
IndexError: list index out of range
`

Any ideas what might be wrong with what I am doing?

Thanks,
Nick

**Comment by sagnikbanerjee15** [comment]
Hi Nick,

Thank you for your interest in `finder`. Could you please post the contents of ~/.bashrc? I think that `finder` might not be in the path. Also, could you run `whereis finder` and post the output here?

Thank you.

**Comment by sivico26** [comment]
Hi, I have exactly the same problem. I installed `finder` just yesterday Following the `git clone` instructions. 

I included `finder` in my .bashrc as instructed:

```shell
$ tail -n1 ~/.bashrc 
export PATH=$PATH:/home/svillanu/Programs/finder
```
Answering your questions (If I may), this is the output of `whereis finder` 
```shell
$ whereis finder
finder:
```
Did you expect it to return the path to `finder`? For that, I use `which` 
```shell
$ which finder
~/Programs/finder/finder
```
To be precise, this is the error I am getting: 
```
Traceback (most recent call last):
  File "/home/svillanu/Programs/finder/finder", line 668, in <module>
    main()
  File "/home/svillanu/Programs/finder/finder", line 606, in main
    validateCommandLineArguments(options,logger_proxy,logging_mutex)
  File "/home/svillanu/Programs/finder/finder", line 181, in validateCommandLineArguments
    finder_directory=open(options.temp_dir+"/finding_finder","r").read().split(":")[-1].split()[-1].strip()
IndexError: list index out of range
```
I hope this helps, and thank you in advance for your help.

**Comment by sagnikbanerjee15** [comment]
Hi @sivico26,

Thanks for reporting the issue. Could you please run the command `export PATH=$PATH:/home/svillanu/Programs/finder`. Both `whereis` and `which` should be able to find the program but things could differ in each distribution. I will try to fix that over the weekend.

Thank you.

**Comment by sivico26** [comment]
@sagnikbanerjee15, the results of those commands are the same I attached in my previous comment.

**Comment by sivico26** [comment]
I changed line 179 of the main executable of `finder` for `cmd="which finder > "+options.temp_dir+"/finding_finder"` and it solve the issue. I can do a pull request If you want. It is a minor thing though, so maybe not worthy of a PR. 

Another problem arose, but I will comment about it in another issue.
