### ISSUE TITLE
I'm not able to do the initial example.

### ISSUE THREAD

**Issue by generalissimodeslock** [sagnikbanerjee15/Finder#26]
Good afternoon.

My name is Fernando, I'm from Brazil and a student of computational biology at Fiocruz.
First of all, I would like to thank you for the initiative to create a software that could predict eukaryotic genes, which was praised by several researchers.

I have a problem, it might even be pathetic of me to do a simple execution using the suggested example.

I'm pasting here the command line I used:

finder -no_cleanup 
-mf **example/Arabidopsis_thaliana_metadata.csv**
-n **4** 
-gdir_olego **example/A_tha**
-out_dir **example/FINDER_test_ARATH**
-g **example/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa**
-p **example/uniprot_ARATH.fasta** 
-gdir_olego olego_index -preserve -pc_clean 1> example/FINDER_test_ARATH.output 2> example/FINDER_test_ARATH.error

Could you please tell me how to proceed, like this example, I'll get other complete genomes. I've been able to perform all the phases up to this point and I'm even embarrassed to ask the software creator for guidance. If possible, could you tell me what I should be aware of when I write the command line?

sorry for bothering and  thank you very much for the information and for providing a very useful software

**Comment by sagnikbanerjee15** [comment]
Hello @generalissimodeslock,

Thank you very much for your interest in `finder`. Please do not apologize for getting stuck. I am certain that there are many more users who are having the same difficulty. Frankly, I can run it without any issues only because I wrote the software!! Let try to troubleshoot.

The command you copy-pasted here looks correct. Could you please tell me the contents of the FINDER_test_ARATH.error file?

Please do not hesitate to contact us. Remember feedbacks like this can improve the quality of software. In fact, we are considering another release where we replace some parts of the pipeline so as to offer users a completely automated solution that can be downloaded via pip and/or conda.

Thank you.

**Comment by generalissimodeslock** [comment]
Thank you very much for replying and i noticed that the program indicates
which line of code is wrong.

I modified 3 things and I think I can now.  If I can't, I'll send you
another answer.

 Thank you.



Em sáb, 25 de set de 2021 18:18, Sagnik Banerjee ***@***.***>
escreveu:

**Comment by generalissimodeslock** [comment]
Goodnight.  I had another question.  Where can csv files that served as
metadata for Arabidopsis thaliana be found?  For example, I want to work
with a protozoan, having the fasta file but not having the other necessary
ones.  Could you help me?

Em sáb, 25 de set de 2021 19:45, Fernando Henrique Silva <
***@***.***> escreveu:

**Comment by sagnikbanerjee15** [comment]
You will have to create the csv files using the data that you have. Also, I am guessing you said protozoan just as an example, FINDER will work only on eukaryotic genomes.

**Comment by generalissimodeslock** [comment]
Good Morning.

Thanks to the tips, watching the FINDER_test_ARATH.error file I managed to redo the entire procedure and for approximately 13 hours the computer I configured to be my server (cpu = 4) was working. Several files were generated, however, when opening the final_GTF_files directory, it was empty

The command line was made in the "example" directory with all the folders indicated inside it, thus:

finder -no_cleanup -mf Arabidopsis_thaliana_metadata.csv -n 4 -gdir_star star_index_without_transcriptome -out_dir FINDER_test_ARATH -g Arabidopsis_thaliana.TAIR10.fa -p uniprot_ARATH.fasta -gdir_olego THDERtest_outervego_index.

Thanks again for the help.

**Comment by sagnikbanerjee15** [comment]
Hello @generalissimodeslock,

Thank you for reporting this. We are trying to enrich the user experience as much as possible. We are on track to release a new version that will address these issues. Could you please compress your output directory and email it to me at sagnikbanerjee15@gmail.com? I need to take a closer look at what is happening. Also, please send the output and the error files.

Thank you.

**Comment by generalissimodeslock** [comment]
Hi good night.

I apologize for not returning the answer as I was worried about writing my
master's dissertation.

I intend to save the generated folders and send them so that what happened
can be analyzed, but if you want a suggestion, if you can make the software
to be installed in an intuitive way as it happens in Anaconda, without the
need for many additional commands, it will be one of the better advances
towards the annotation of eukaryotic genomes.

Thank you so much for remembering our conversation.

Em ter., 12 de out. de 2021 às 21:33, Sagnik Banerjee <
***@***.***> escreveu:

**Comment by sagnikbanerjee15** [comment]
Hello @generalissimodeslock,

No need to apologize. Take your time to write your master's dissertation. We can work on this later as well. Just let me know when you have time.

I completely agree with you about changing the way the installation occurs. We are trying our best to ensure the installation process is the least complicated. We have decided to let go of some of our software to ease installation.

Thank you.

**Comment by DomeJoyce** [comment]
Hello @sagnikbanerjee15 ,

I'm having problems using the example dataset, as well as using my real and local data.
As reported in your guide, I run the following command:
finder -no_cleanup -mf Arabidopsis_thaliana_metadata.csv -n $CPU -gdir_star $PWD/star_index_without_transcriptome -out_dir $PWD/FINDER_test_ARATH -g $PWD/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa -p $PWD/uniprot_ARATH.fasta -gdir_olego olego_index -preserve 1> $PWD/FINDER_test_ARATH.output 2> $PWD/FINDER_test_ARATH.error

Here the content of finder_v1.0.0/example/FINDER_test_ARATH.error

cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_round2_SJ.out.tab: File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_final_Log.final.out': File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_round3_SJ.out.tab: File o directory non esistente
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data1_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data2_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data1_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data2_round2_SJ.out.tab: File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data1_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data2_final_Log.final.out': File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data1_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data2_round3_SJ.out.tab: File o directory non esistente
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_round1_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_round2_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_round2_SJ.out.tab: File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_final_Log.final.out': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_final_Unmapped.out.mate1': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_final_Unmapped.out.mate2': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_final_Log.final.out': File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_round3_SJ.out.tab: File o directory non esistente
cat: /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_round3_SJ.out.tab: File o directory non esistente
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
samtools index: "/home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_final.sortedByCoord.out.bam" is in a format that cannot be usefully indexed
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197913_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197914_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422202_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422200_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR5197915_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844300_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844296_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR9844295_final.sortedByCoord.out.bam.
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Can not open /home/software/finder_v1.0.0/example/FINDER_test_ARATH/alignments/SRR8422201_final.sortedByCoord.out.bam.
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_0.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_1.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_2.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_3.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_4.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_5.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_6.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_7.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_8.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_9.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_10.gtf': File o directory non esistente
mv: impossibile eseguire stat di '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_vote.gtf': File o directory non esistente
Traceback (most recent call last):
  File "/home/software/finder_v1.0.0/finder", line 679, in <module>
    main()
  File "/home/software/finder_v1.0.0/finder", line 640, in main
    orchestrateGeneModelPrediction(options,logger_proxy,logging_mutex)
  File "/home/software/finder_v1.0.0/finder", line 453, in orchestrateGeneModelPrediction
    findTranscriptsInEachSampleNotReportedInCombinedAnnotations(options,logger_proxy,logging_mutex)
  File "/home/software/finder_v1.0.0/scripts/findTranscriptsInEachSampleNotReportedInCombinedAnnotations.py", line 17, in findTranscriptsInEachSampleNotReportedInCombinedAnnotations
    combined_transcript_info=readAllTranscriptsFromGTFFileInParallel([combined_gtf_filename,"combined","combined"])[0]
  File "/home/software/finder_v1.0.0/scripts/fileReadWriteOperations.py", line 279, in readAllTranscriptsFromGTFFileInParallel
    fhr=open(gtf_filename,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/software/finder_v1.0.0/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/combined.gtf'

Attached you find also the progress.log

[progress.log](https://github.com/sagnikbanerjee15/Finder/files/7704542/progress.log)

Can you help me to fix this problem?

I saw the same mapping problem using my local data

**Comment by sagnikbanerjee15** [comment]
Hello @DomeJoyce,

Thank you so much for your interest in `finder`. There might be an issue in a number of steps. Could you please email me the compressed output folder at sagnikbanerjee15@gmail.com? I need to take a closer look at the contents.

Thank you.

**Comment by DomeJoyce** [comment]
Hello @sagnikbanerjee15 ,

Thank you for your support!
I just sent the email containing the output folder requested.

Best!

**Comment by deniskristak** [comment]
@sagnikbanerjee15 Hello, just noticed this might be related to my problem...is there anything you might share about this issue?

**Comment by generalissimodeslock** [comment]
Good afternoon.

Thank you for contacting you and really, in that version of the program had
errors and did not complete the execution.

I really want to see the progress and change that was made on the pipeline.

Please, I could tell me the link in the Github or the Conde I intend to do
the tests in it a little later.

thanks.

**Comment by sagnikbanerjee15** [comment]
Hello @DomeJoyce and @generalissimodeslock,

I'm sorry for not getting back to you sooner. I have yet to be able to make much progress in troubleshooting the software. We are inviting collaborators to help address the issues and redesign the architecture of FINDER. We are trying our best to restart development on this again. I apologize for the delay.

Thank you.

**Comment by generalissimodeslock** [comment]
Hi good morning.

My dear, it is normal to take so long because it is rewriting software from
scratch and that many people are not interested in collaborating. This is
discouraging.

What I propose is that Finder only has auxiliary software that does not
need special academic license, avoiding the need for updates linked to
other institutions.

Another point I have already suggested is that it is, just as it is linked
to Github, that Finder is linked to Bioconda, which would greatly
facilitate the installation and auxiliary packages.

In addition, I offer to test Finder in all versions, so that you can act
and meet the annotation of eukaryotic genomes of different species.

I wish success.

Em dom, 15 de jan de 2023 23:48, Sagnik Banerjee ***@***.***>
escreveu:
