### ISSUE TITLE
Finder failed to analy

### ISSUE THREAD

**Issue by jb018** [sagnikbanerjee15/Finder#37]
Hi Sagnik

I'm trying to run finder on the provided example data. However, it's just failing and trowing the following error.

Any help is appreciated. 

finder -no_cleanup -mf test_metadata.csv -n 30 -gdir_star $PWD/star_index_without_transcriptome -out_dir $PWD/FINDER_test_ARATH -g $PWD/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa -p $PWD/uniprot_ARATH.fasta -gdir_olego olego_index -preserve
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_olego_round5.sorted.bam
samtools merge: fail to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_olego_round5.sorted.bam": No such file or directory
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_olego_round5.sorted.bam
samtools merge: fail to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_olego_round5.sorted.bam": No such file or directory
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam
samtools index: failed to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam": No such file or directory
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam
samtools index: failed to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam": No such file or directory
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam
samtools index: failed to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam": No such file or directory
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam
samtools index: failed to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam": No such file or directory
open: No such file or directory
open: No such file or directory
open: No such file or directory
open: No such file or directory
sh: line 1: 148093 Segmentation fault      (core dumped) /data/apps/finder/dep/psiclass_terminal_exon_length_modified//subexon-info /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_introns --noStats > /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_exons
sh: line 1: 148092 Segmentation fault      (core dumped) /data/apps/finder/dep/psiclass_terminal_exon_length_modified//subexon-info /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_introns --noStats > /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_exons
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam
samtools view: failed to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam
samtools view: failed to open "/data/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam" for reading: No such file or directory
mv: cannot stat ‘/data/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_0.gtf’: No such file or directory
mv: cannot stat ‘/data/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_1.gtf’: No such file or directory
mv: cannot stat ‘/data/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_vote.gtf’: No such file or directory
Traceback (most recent call last):
  File "/data/apps/finder/finder", line 675, in <module>
    main()
  File "/data/apps/finder/finder", line 636, in main
    orchestrateGeneModelPrediction(options,logger_proxy,logging_mutex)
  File "/data/apps/finder/finder", line 449, in orchestrateGeneModelPrediction
    findTranscriptsInEachSampleNotReportedInCombinedAnnotations(options,logger_proxy,logging_mutex)
  File "/data/apps/finder/scripts/findTranscriptsInEachSampleNotReportedInCombinedAnnotations.py", line 17, in findTranscriptsInEachSampleNotReportedInCombinedAnnotations
    combined_transcript_info=readAllTranscriptsFromGTFFileInParallel([combined_gtf_filename,"combined","combined"])[0]
  File "/data/apps/finder/scripts/fileReadWriteOperations.py", line 279, in readAllTranscriptsFromGTFFileInParallel
    fhr=open(gtf_filename,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/data/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/combined.gtf'

Kind regards

**Comment by sagnikbanerjee15** [comment]
Hello @jb018,

Thank you so much for your interest in `finder`. The issue seems to be around the Olego aligner. Could you please check that Olego is properly installed within the conda environment? Please issue the command `olegoindex` and let me know the output.

Thank you.

**Comment by jb018** [comment]
Thanks for your prompt response @sagnikbanerjee15 

olegoindex doesn't show any error. correct me if I'm wrong. Pasting the output as shown below for your reference.



 ../dep/olego/olegoindex -p olego_index Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa 
[bwa_index] Pack FASTA... 0.73 sec
[bwa_index] Reverse the packed sequence... 0.28 sec
[bwa_index] Construct BWT for the packed sequence...
[BWTIncConstructFromPacked] 10 iterations done. 29216662 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 51116486 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 68388582 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 82010006 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 92751542 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 101221302 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 107898902 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 113162758 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 117311366 characters processed.
[bwt_gen] Finished constructing BWT in 97 iterations.
[bwa_index] 40.41 seconds elapse.
[bwa_index] Construct BWT for the reverse packed sequence...
[BWTIncConstructFromPacked] 10 iterations done. 29216662 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 51116486 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 68388582 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 82010006 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 92751542 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 101221302 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 107898902 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 113162758 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 117311366 characters processed.
[bwt_gen] Finished constructing BWT in 97 iterations.
[bwa_index] 40.56 seconds elapse.
[bwa_index] Update BWT... 0.28 sec
[bwa_index] Update reverse BWT... 0.31 sec
[bwa_index] Construct SA from BWT and Occ... 6.26 sec
[bwa_index] Construct SA from reverse BWT and Occ... 6.29 sec


====================================

Just checking the file size of olego index otputs (seems to be fine).

ls olego_index.* -Ssh
 43M olego_index.bwt   43M olego_index.rbwt   29M olego_index.pac   29M olego_index.rpac   15M olego_index.rsa   15M olego_index.sa  7.5K olego_index.amb  1.0K olego_index.ann


Thanks

**Comment by sagnikbanerjee15** [comment]
Hmm. Looks like the installation was successful. Could you send me a screenshot of the ls -lhrt for the bam files in the output directory.

Thank you.

**Comment by jb018** [comment]
Please find as shown below

ls FINDER_test_ARATH/alignments/ -lhrt
total 174K
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:02 dummy_data1_round1.error
-rw-rw-r-- 1 jb018 jb018  772 Nov 22 00:03 dummy_data1_round1_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018  30K Nov 22 00:03 dummy_data1_round1_Aligned.sortedByCoord.out.bam
-rw-rw-r-- 1 jb018 jb018 2.0K Nov 22 00:03 dummy_data1_round1_Log.final.out
-rw-rw-r-- 1 jb018 jb018  15K Nov 22 00:03 dummy_data1_round1_Unmapped.out.mate1
-rw-rw-r-- 1 jb018 jb018  239 Nov 22 00:03 dummy_data1_round1.output
drwx------ 3 jb018 jb018    0 Nov 22 00:03 dummy_data1_round1__STARtmp
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_round1.error
-rw-rw-r-- 1 jb018 jb018  772 Nov 22 00:03 dummy_data2_round1_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018  30K Nov 22 00:03 dummy_data2_round1_Aligned.sortedByCoord.out.bam
-rw-rw-r-- 1 jb018 jb018 2.0K Nov 22 00:03 dummy_data2_round1_Log.final.out
-rw-rw-r-- 1 jb018 jb018  15K Nov 22 00:03 dummy_data2_round1_Unmapped.out.mate1
-rw-rw-r-- 1 jb018 jb018  239 Nov 22 00:03 dummy_data2_round1.output
drwx------ 3 jb018 jb018    0 Nov 22 00:03 dummy_data2_round1__STARtmp
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 leaf_round1_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_round2.error
drwx------ 2 jb018 jb018    0 Nov 22 00:03 dummy_data1_round2__STARgenome
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_round2_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018  932 Nov 22 00:03 dummy_data1_round2_Aligned.sortedByCoord.out.bam
-rw-rw-r-- 1 jb018 jb018 2.0K Nov 22 00:03 dummy_data1_round2_Log.final.out
-rw-rw-r-- 1 jb018 jb018  15K Nov 22 00:03 dummy_data1_round2_Unmapped.out.mate1
-rw-rw-r-- 1 jb018 jb018  239 Nov 22 00:03 dummy_data1_round2.output
drwx------ 3 jb018 jb018    0 Nov 22 00:03 dummy_data1_round2__STARtmp
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_round2.error
drwx------ 2 jb018 jb018    0 Nov 22 00:03 dummy_data2_round2__STARgenome
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_round2_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018  932 Nov 22 00:03 dummy_data2_round2_Aligned.sortedByCoord.out.bam
-rw-rw-r-- 1 jb018 jb018 2.0K Nov 22 00:03 dummy_data2_round2_Log.final.out
-rw-rw-r-- 1 jb018 jb018  15K Nov 22 00:03 dummy_data2_round2_Unmapped.out.mate1
-rw-rw-r-- 1 jb018 jb018  239 Nov 22 00:03 dummy_data2_round2.output
drwx------ 3 jb018 jb018    0 Nov 22 00:03 dummy_data2_round2__STARtmp
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 leaf_round2_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 leaf_round1_and_round2_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_round3.error
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_round3_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018  886 Nov 22 00:03 dummy_data1_round3_Aligned.sortedByCoord.out.bam
-rw-rw-r-- 1 jb018 jb018 2.0K Nov 22 00:03 dummy_data1_round3_Log.final.out
-rw-rw-r-- 1 jb018 jb018  15K Nov 22 00:03 dummy_data1_round3_Unmapped.out.mate1
-rw-rw-r-- 1 jb018 jb018  239 Nov 22 00:03 dummy_data1_round3.output
drwx------ 3 jb018 jb018    0 Nov 22 00:03 dummy_data1_round3__STARtmp
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_round3.error
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_round3_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018  886 Nov 22 00:03 dummy_data2_round3_Aligned.sortedByCoord.out.bam
-rw-rw-r-- 1 jb018 jb018 2.0K Nov 22 00:03 dummy_data2_round3_Log.final.out
-rw-rw-r-- 1 jb018 jb018  15K Nov 22 00:03 dummy_data2_round3_Unmapped.out.mate1
-rw-rw-r-- 1 jb018 jb018  239 Nov 22 00:03 dummy_data2_round3.output
drwx------ 3 jb018 jb018    0 Nov 22 00:03 dummy_data2_round3__STARtmp
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 leaf_round3_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 leaf_round1_and_round2_and_round3_SJ.out.tab
-rw-rw-r-- 1 jb018 jb018  273 Nov 22 00:03 dummy_data1_round5.error
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_olego_round5.sorted.bam2
-rw-rw-r-- 1 jb018 jb018  273 Nov 22 00:03 dummy_data2_round5.error
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_olego_round5.sorted.bam2
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_introns
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_introns
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_introns.bed
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_introns.bed
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_exons
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_exons
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_exons.bed
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_exons.bed
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_num_exons_in_intron
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_num_exons_in_intron
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_final.sortedByCoord.out.sam
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_final.sortedByCoord.out.sam
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data2_for_psiclass.sam
-rw-rw-r-- 1 jb018 jb018    0 Nov 22 00:03 dummy_data1_for_psiclass.sam
-rw-rw-r-- 1 jb018 jb018   71 Nov 22 00:03 dummy_data1_for_psiclass.bam
-rw-rw-r-- 1 jb018 jb018   71 Nov 22 00:03 dummy_data2_for_psiclass.bam
-rw-rw-r-- 1 jb018 jb018  345 Nov 22 00:03 mapping_stats.csv


===============================================



cat  FINDER_test_ARATH/alignments/mapping_stats.csv 
Bioproject,Run,condition,Total reads,Round1_umr,Round1_mmr,Round1_tmr,Round2_umr,Round2_mmr,Round2_tmr,Round3_umr,Round3_mmr,Round3_tmr,round4_umr,round4_mmr,round4_tmr
Dummy1,dummy_data1,leaf,250,0.76,0.04,0.81,0.76,0.04,0.81,0.76,0.04,0.81,0.76,0.04,0.81
Dummy2,dummy_data2,leaf,250,0.76,0.04,0.81,0.76,0.04,0.81,0.76,0.04,0.81,0.76,0.04,0.81

**Comment by sagnikbanerjee15** [comment]
Hello @jb018,

Thank you for posting the output. I noticed that the bam file output `dummy_data2_olego_round5.sorted.bam2` has a 2 in the end which is leading to the failure. Could you do a git pull and rerun it? I fixed this issue about a week back.

Please let me know if you encounter any more issues. Just to let you know, I am working to release a new version as a docker image. Hopefully, that will address most of these issues.

Thank you.

**Comment by jb018** [comment]
Hi @sagnikbanerjee15 

Yes, I took a notice on the recent release and updated it too. However, still it fails. I did git pull, it also confirm its up to date.

git pull
Already up-to-date.git pull

Many thanks

**Comment by sagnikbanerjee15** [comment]
Hi @jb018,

Thanks for your reply. Could you please remove the folder and do a fresh download?

Thanks.

**Comment by jb018** [comment]
Hi @sagnikbanerjee15 

I re-installed from scratch and run it again, but I get the same error

example]$ ../finder -no_cleanup -mf Arabidopsis_thaliana_metadata.csv -n $CPU -gdir_star $PWD/star_index_without_transcriptome -out_dir $PWD/FINDER_test_ARATH -g $PWD/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa -p $PWD/uniprot_ARATH.fasta -gdir_olego olego_index -preserve 
[E::hts_open_format] Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_olego_round5.sorted.bam
samtools merge: fail to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_olego_round5.sorted.bam": No such file or directory
[E::hts_open_format] Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_olego_round5.sorted.bam
samtools merge: fail to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_olego_round5.sorted.bam": No such file or directory
[E::hts_open_format] Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam
samtools index: failed to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam": No such file or directory
[E::hts_open_format] Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam
samtools index: failed to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam": No such file or directory
[E::hts_open_format] Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam
samtools index: failed to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam": No such file or directory
[E::hts_open_format] Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam
samtools index: failed to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam": No such file or directory
open: No such file or directory
open: No such file or directory
open: No such file or directory
open: No such file or directory
sh: line 1: 52497 Segmentation fault      (core dumped) /apps/finder/dep/psiclass_terminal_exon_length_modified//subexon-info /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_introns --noStats > /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_exons
sh: line 1: 52496 Segmentation fault      (core dumped) /apps/finder/dep/psiclass_terminal_exon_length_modified//subexon-info /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_introns --noStats > /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_exons
[E::hts_open_format] Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam
samtools view: [E::hts_open_format] failed to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data1_final.sortedByCoord.out.bam" for reading: No such file or directory
Failed to open file /apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam
samtools view: failed to open "/apps/finder/example/FINDER_test_ARATH/alignments/dummy_data2_final.sortedByCoord.out.bam" for reading: No such file or directory
mv: cannot stat ‘/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_0.gtf’: No such file or directory
mv: cannot stat ‘/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_sample_1.gtf’: No such file or directory
mv: cannot stat ‘/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/psiclass_output_vote.gtf’: No such file or directory
Traceback (most recent call last):
  File "../finder", line 675, in <module>
    main()
  File "../finder", line 636, in main
    orchestrateGeneModelPrediction(options,logger_proxy,logging_mutex)
  File "../finder", line 449, in orchestrateGeneModelPrediction
    findTranscriptsInEachSampleNotReportedInCombinedAnnotations(options,logger_proxy,logging_mutex)
  File "/apps/finder/scripts/findTranscriptsInEachSampleNotReportedInCombinedAnnotations.py", line 17, in findTranscriptsInEachSampleNotReportedInCombinedAnnotations
    combined_transcript_info=readAllTranscriptsFromGTFFileInParallel([combined_gtf_filename,"combined","combined"])[0]
  File "/apps/finder/scripts/fileReadWriteOperations.py", line 279, in readAllTranscriptsFromGTFFileInParallel
    fhr=open(gtf_filename,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/apps/finder/example/FINDER_test_ARATH/assemblies_psiclass_modified/combined/combined.gtf'


Any help is appreciated !!

Thanks

**Comment by sagnikbanerjee15** [comment]
Hello @jb018,

Well, this is unexpected. Could you please send me the output folder and the folder you downloaded? You can email me those to sagnikbanerjee15@gmail.com. 

I would have created a docker image to eliminate these problems but the current version of `finder` depends on a few software that are not permitted to be redistributed.

Thank you.

**Comment by jb018** [comment]
Thanks @sagnikbanerjee15 

Just sent you an email.

Many thanks
