### ISSUE TITLE
cds_predict error

### ISSUE THREAD

**Issue by claumer** [sagnikbanerjee15/Finder#44]
Hello there,

I'm trying to use FINDER for the first time, on a Drosophila de novo assembly with locally stored RNA-seq data. Many parts of the pipeline seem to have worked using the installation and run guidance as documented - for instance BRAKER has finished - but I find an error in step 5 of the pipeline that I can't work out how to overcome:

INFO:    Creating SIF file...
Traceback (most recent call last):
  File "/softwares/FINDER/Finder/finder", line 688, in <module>
    main()
  File "/softwares/FINDER/Finder/finder", line 665, in main
    findCDS( options, logger_proxy, logging_mutex )
  File "/softwares/FINDER/Finder/scripts/predictCDS.py", line 66, in findCDS
    fhr = open( options.output_assemblies_psiclass_terminal_exon_length_modified + "/combined/cds_predict/annotation.gtf", "r" )
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/scratch116/tol/teams/team301/users/cl16/Drosophila/idDroSubo1_FINDER/assemblies_psiclass_modified/combined/cds_predict/annotation.gtf'

Indeed, if I go to /idDroSub1_FINDER/assemblies_psiclass_modified/combined/cds_predict/ I see only:

-rw-r--r-- 1 cl16 team301 38219274 Jan 12 11:53 minus.fa
-rw-r--r-- 1 cl16 team301        0 Jan 12 11:53 ORFs_minus.gtf
-rw-r--r-- 1 cl16 team301        0 Jan 12 11:53 ORFs_plus.gtf

I also notice an error from running Codan in the combined/ directory:

Traceback (most recent call last):
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 524, in <module>
    __main__()
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 506, in __main__
    _codan_BOTH_(options.transcripts, options.output_folder, options.model, options.cpu)
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 355, in _codan_BOTH_
    _retrieveORF_BOTH_(transcripts, outF+"minus.fa", outF)
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 147, in _retrieveORF_BOTH_
    record_dictP = SeqIO.index(transcripts, "fasta")
  File "/usr/lib/python3/dist-packages/Bio/SeqIO/__init__.py", line 979, in index
    return _IndexedSeqFileDict(
  File "/usr/lib/python3/dist-packages/Bio/File.py", line 350, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'u000001431.46339_3_covsplit.0'

Can you please advise on what might have gone wrong here, and what should be done to fix it? Happy to provide any intermediate files needed to diagnose. I'm running on an HPC cluster using singularity 3.9.0.

Regards,
Chris L

**Comment by claumer** [comment]
Hello Sagnik,

Apologies for the delay in getting back, we've been having major i/o problems on the filesystem my run was stored on so it's been hard to access my files. But now I've tarballed the assemblies_psiclass_modified directory - you should be able to download it here:

https://1drv.ms/u/s!AvwOlP_fkZlggapIskAoXfWIUPtNoA?e=yeAfNa

Thanks very much for your help looking into this. I'd love to have a crack at using FINDER if there's a fix for this!

Regards,
Chris L

**Comment by sagnikbanerjee15** [comment]
Hello @claumer,

Thank you for getting me the files. I inspected the results and understood what the problem was. I have modified the code to remove the issue. Could you please try it again and let me know if the issue still persists?

Thank you.

**Comment by claumer** [comment]
Hello again Sagnik,

I have tried again with the most recent code from this github repository, deleting the assemblies_psiclass_modified directory and starting again, and am sorry to tell you that the run has failed again, in what looks to my eyes like exactly the same way.

What do you suggest? If needed I could try to get my base files to you, though of course they will be large...

Regards,
Chris L

**Comment by sagnikbanerjee15** [comment]
Hello @claumer,

It would be great if you could share with me the base files. I will try executing FINDER on those. 

Thank you.
