### ISSUE TITLE
Genome examples empty?

### ISSUE THREAD

**Issue by paul-bio** [sagnikbanerjee15/Finder#47]
Hi I am trying to predict gene structure using Finder.
And it seems this tool is better than PASA, MAKER,,,
So I am planning to get used to this tool.

However, the example data you shared, I could get metadata, protein data, and rawdata but could not find genome data. Where can I find the genome sequence?

Thanks a lot for us to use this beautiful tool.
Sincerely, Paul.

**Comment by sagnikbanerjee15** [comment]
Hello @paul-bio,

Thank you so much for your interest in `finder`. You have to download the genome file from this link -> http://ftp.ensemblgenomes.org/pub/plants/release-52/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa.gz. Currently, I am a bit busy with my work. I will make changes to the README file later. Also, please make sure you enter the correct location of the directory for the dummy data in metadata.csv file. It should be the location where you performed the git pull.

Please let us know if you encounter any issues while running the software.

Thank you

**Comment by sagnikbanerjee15** [comment]
Hello Paul,

Thanks for posting the error message. There are a few tweaks you need to make to the command that you are running. Firstly, it should be `metadata.csv`, not `metadata.xlsx`. Secondly, could you please make sure that the genome is in fact present in the current directory? I always provide the whole path (from /) to a program. That way I can execute it from anywhere and not really worry about changing anything. It seems that `finder` cannot locate the genome file. Thirdly, the command you should execute is `run_finder` and not `finder`. `run_finder` will check your system for the presence of docker or singularity. Depending on which one is available it will execute `finder`. 

`data2.fastq.gz` is a compressed fastq file. If you open it up you will see some garbled text which is expected since the data is binary format not human-readable. I included that in the example run to demonstrate that `finder` can work with compressed RNA-Seq samples as well.

Please let me know if you run into any further problems.

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello @paul-bio,

Thank you for posting this. Could you please confirm that you have either singularity or docker installed on your system? Please paste the outputs of `which docker` and `which singularity`. Are you running this on your personal computer or on a computational cluster?

Thank you.

**Comment by paul-bio** [comment]
I am currently running on a computational cluster.
And I am used to work in conda environment, but there were none.

First I downloaded FINDER with wget as below 
$wget https://github.com/sagnikbanerjee15/Finder/archive/refs/tags/finder_v1.1.0.tar.gz

since run_finder works with docker, I used finder instead

And get GeneMart key and files from website.


Thank you.

**Comment by sagnikbanerjee15** [comment]
Actually, the docker image has all the software preinstalled. `finder` will not work on a conda environment since that is not maintained anymore.

Hope that helps!

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello @paul-bio,

Could you please try again after removing the output directory? Also, please send me the contents of the file /NFS2/users/creo9447/software/FINDER/example/Arabidopsis_thaliana_metadata.csv

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello @paul-bio,

Thanks for your reply. And please do not hesitate to ask questions. Feedback like this will make `finder` even better. 

I looked at the metadata.csv file and it seems everything is correct. Is there any reason why you are running the example with only one RNA-Seq dataset? 

Could you send me the output of the command `ls -lhrt /NFS2/users/creo9447/software/FINDER/example/FINDER/alignments` ? And also the progress.log file.

Thank you.

**Comment by sagnikbanerjee15** [comment]
Hello @paul-bio,

Thank you for deciding to use `finder` in your project. I would recommend that you use the entire metadata.csv file and not just the dummy data. The dummy data contain very few reads which are not enough to generate any annotations. The reason for including those data is to ensure that the pipeline can process locally available data. Don't worry about not having the rest of the data. `finder` will automatically download those from NCBI SRA. This is the command you should try:

```
# Remove the output directory
rm -rf /NFS2/users/creo9447/software/FINDER/example/FINDER

# Run the program with the entire metadata

$run_finder -mf /NFS2/users/creo9447/software/FINDER/example/Arabidopsis_thaliana_metadata.csv -out_dir /NFS2/users/creo9447/software/FINDER/example/FINDER -g /NFS2/users/creo9447/software/FINDER/example/Arabidopsis_thaliana.TAIR10.dna_sm.toplevel.fa --protein /NFS2/users/creo9447/software/FINDER/example/uniprot_ARATH.fasta -om PLANTS --genemark_path /NFS2/users/creo9447/software/GeneMark/gmes_linux_64/ --genemark_license /NFS2/users/creo9447/software/GeneMark/gm_key_64 --cpu 32 --framework docker
```

Please let me know if this works.

Thank you.

**Comment by paul-bio** [comment]
Hi again.
With command you suggested, still a error message came out.
And it seems there is a problem in .gm_key when running braker.
Here is the braker.error, progress.log and the error message i got.
[braker.error.txt](https://github.com/sagnikbanerjee15/Finder/files/8053985/braker.error.txt)
[progress.log](https://github.com/sagnikbanerjee15/Finder/files/8053986/progress.log)
age i got.

Trying to pull repository docker.io/sagnikbanerjee15/finder ...
1.1.0: Pulling from docker.io/sagnikbanerjee15/finder
Digest: sha256:9816d258d2421d4625983c929f508b1f577cfe7ab3bc2042e841647a186c7931
Status: Image is up to date for docker.io/sagnikbanerjee15/finder:1.1.0
done
rm: cannot remove '/NFS2/users/creo9447/software/FINDER/example/FINDER/assemblies_psiclass_modified/combined/outputfileforCPD_*': No such file or directory
Traceback (most recent call last):
  File "/softwares/FINDER/Finder/finder", line 688, in <module>
    main()
  File "/softwares/FINDER/Finder/finder", line 673, in main
    addBRAKERPredictions( options, logger_proxy, logging_mutex )
  File "/softwares/FINDER/Finder/scripts/predictGenesUsingBRAKER.py", line 287, in addBRAKERPredictions
    fhr = open( options.output_assemblies_psiclass_terminal_exon_length_modified + "/proteins_comparison_gffcompare.proteins_for_alignment.gtf.refmap", "r" )
FileNotFoundError: [Errno 2] No such file or directory: '/NFS2/users/creo9447/software/FINDER/example/FINDER/assemblies_psiclass_modified/proteins_comparison_gffcompare.proteins_for_alignment.gtf.refmap'

I also noticed that in your github you said I have to get GeneMark-ES/ET/EP ver 4.62. However in the website link, a new version of 4.69 is currently available. Is it possible the error kept emerging is because of different version?

**Comment by paul-bio** [comment]
HI @sagnikbanerjee15

I changed my metadata.csv. And this time I have lot more error than previous runs.
[Arabidopsis_thaliana_metadata.csv](https://github.com/sagnikbanerjee15/Finder/files/8055263/Arabidopsis_thaliana_metadata.csv)

[error_message.txt](https://github.com/sagnikbanerjee15/Finder/files/8055262/error_message.txt)

And used this metadata file. 
I don't think now there is no problem in metadata nor raw data.
[Arabidopsis_thaliana_metadata.csv](https://github.com/sagnikbanerjee15/Finder/files/8055263/Arabidopsis_thaliana_metadata.csv)


Thanks.

**Comment by sagnikbanerjee15** [comment]
Hello @paul-bio,

Thanks for posting the error. The command looks good and so does the metadata file. I will need some time to figure out the problem. I will let you know when I am done.

Thank you.

**Comment by paul-bio** [comment]
Thanks @sagnikbanerjee15 
I hope the problem fixed soon.

Thanks a lot.
