### ISSUE TITLE
Finder generates no files and fails

### ISSUE THREAD

**Issue by ereyred** [sagnikbanerjee15/Finder#75]
Hello, I'm running Finder from local installation, not Docker. I'm running with PE RNAseq.fq but no protein file. It makes the necessary output directories and protein dummy file in temp but no other output and it gives me the following error:

_Status: Downloaded newer image for sagnikbanerjee15/finder:1.1.0
docker.io/sagnikbanerjee15/finder:1.1.0
done
Traceback (most recent call last):
  File "/softwares/FINDER/Finder/finder", line 688, in <module>
    main()
  File "/softwares/FINDER/Finder/finder", line 637, in main
    readMetaDataFile( options, logger_proxy, logging_mutex )
  File "/softwares/FINDER/Finder/scripts/fileReadWriteOperations.py", line 138, in readMetaDataFile
    small_rna_samples[condition][Run] = {"bioproject":BioProject,
KeyError: ''_

The progress.log out put is:
_2023-03-19 23:53:40,489 - finder -   INFO - Running command - perl 
/Finder_v1.1.0/gmes_linux_64//change_path_in_perl_scripts.pl "/usr/bin/env perl"
2023-03-19 23:53:40,916 - finder -   INFO - Software paths have been set
2023-03-19 23:53:41,498 - finder -   INFO - Generating STAR index
2023-03-19 23:53:41,909 - finder -   INFO - Running cmd - STAR  --runThreadN 20 --runMode genomeGenerate  --genomeDir 
/Finder_v1.1.0/output/indices/star_index_without_transcriptome --genomeFastaFiles /Finder_v1.1.0/output/Genome.fasta.masked --genomeChrBinNbits 18 --genomeSAindexNbases 11.740410536216816 --outFileNamePrefix 
/Finder_v1.1.0/output/alignments/indexGenome > /Finder_v1.1.0/output/indices/star_index_without_transcriptome.output  2> /Finder_v1.1.0/output/indices/star_index_without_transcriptome.error 
2023-03-19 23:53:56,972 - finder -   INFO - STAR index generation complete
2023-03-19 23:53:56,973 - finder -   INFO - Generating OLego index
2023-03-19 23:53:56,974 - finder -   INFO - Running cmd - olegoindex -p 
/Finder_v1.1.0/output/indices/olego_index /Finder_v1.1.0/Genome.fasta.masked > /Finder_v1.1.0/output/indices_olego_index.output  2> /Finder_v1.1.0/output/indices_olego_index.error 
2023-03-19 23:54:59,284 - finder -   INFO - OLego index built
2023-03-19 23:54:59,286 - finder -   INFO - Adding dummy file since no protein evidence was provided
2023-03-19 23:54:59,286 - finder -   INFO - validateCommandLineArguments execution successful_

My metadata file looks like this:
BioProject	SRA Accession	Tissues	Description	Date	Read Length (bp)	Ended	RNA Seq	process	Location
Name	        S1_8	                                na			                                        	PE	        1	        1	        /dir/Finder_v1.1.0/

Thanks for your help!
E

**Comment by sagnikbanerjee15** [comment]
Hello @ereyred,

Thank you for your interest in `finder`. We are aware of the issues in the previous version but we have decided to move forward with new improvements. As of now, we do not have any plans of fixing the issues in the previous version since they will be taken cared of in the new version.

Thank you.
