### ISSUE TITLE
codan fails and kills pipeline due to finding duplicate key(s)

### ISSUE THREAD

**Issue by laurabaxter21** [sagnikbanerjee15/Finder#76]
Running the latest run_finder-v1.1.0.
Everything runs fine until the codan step (Braker is complete), which finds a duplicate key and kills the pipeline.
Looking at the assemblies_psiclass_modified/combined/combined_split_transcripts_with_bad_SJ_redundancy_removed.fasta file for duplicated sequence IDs, I find 2 (C2.27447_0_covsplit.0 and C7.149167_0_covsplit.0, both with different sequences in each of the duplicates).

Could I just delete these out from FASTA/gtf and continue from checkpoint 5?

assemblies_psiclass_modified/combined/cds_predict.error:

Traceback (most recent call last):
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 524, in <module>
    __main__()
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 506, in __main__
    _codan_BOTH_(options.transcripts, options.output_folder, options.model, options.cpu)
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 355, in _codan_BOTH_
    _retrieveORF_BOTH_(transcripts, outF+"minus.fa", outF)
  File "/softwares/CODAN/CodAn-1.2/bin/codan.py", line 147, in _retrieveORF_BOTH_
    record_dictP = SeqIO.index(transcripts, "fasta")
  File "/usr/lib/python3/dist-packages/Bio/SeqIO/__init__.py", line 979, in index
    return _IndexedSeqFileDict(
  File "/usr/lib/python3/dist-packages/Bio/File.py", line 350, in __init__
    raise ValueError("Duplicate key '%s'" % key)
ValueError: Duplicate key 'C2.27447_0_covsplit.0'

**Comment by sagnikbanerjee15** [comment]
Hello @laurabaxter21,

Thank you very much for your interest in `finder`. We have decided to focus our attention on developing the 2nd version of the software. As of now, we do not have the capabilities to support the older version due to a lack of personnel and I sincerely apologize for that. If you want to follow up on this please email me at sagnikbanerjee15@gmail.com and I will do my best to help you out.

Thank you.

**Comment by laurabaxter21** [comment]
Hi,  yes I recall I just deleted the offending duplicated sequences from the FASTA file and their corresponding entries from the gft file (they didn't seem critically important). Then I re-ran finder from checkpoint 5 and it completed OK.

Hope that helps,
Laura
________________________________
