### ISSUE TITLE
Finder does not find files (supposed to be) generated at earlier steps...

### ISSUE THREAD

**Issue by lefterov** [sagnikbanerjee15/Finder#80]
We are running finder at the command line. Now we know that the "Required parameters" as in the help file, and if provided in an empty directory do not work, and we have solved that problem... However, with this command:

**finder  -mf $PWD/ev-mRNA-metadata_1002_10AM.csv -n 118 -out_dir $PWD/output_1002 -g $PWD/mm10.fa -om VERT -gm $PWD/gmes_linux_64_4 -gml $PWD/gmes_linux_64_4/LICENSE**

we get this Error message:

'FileNotFoundError: [Errno 2] No such file or directory: $PWD/output_1002/assemblies_psiclass_modified/combined/combined.gtf'

we don't know how to generate this file... :)

any idea how to solve the problem?

Thanks, and have a nice evening.

**Comment by sagnikbanerjee15** [comment]
Hi @lefterov,

Thank you very much for your interest in `finder`. Could you please check your error files? We have witnessed cases where the pipeline continues after failing.

Thanks.

**Comment by lefterov** [comment]
Thank you Sagnik,

This time we ran Finder in a Container using Singularity on a machine with 128 cores. The run stopped at the generation of the SIF file with the following Error:

INFO:    Creating SIF file...
Traceback (most recent call last):
  File "/softwares/FINDER/Finder/finder", line 688, in <module>
    main()
  File "/softwares/FINDER/Finder/finder", line 628, in main
    validateCommandLineArguments( options, logger_proxy, logging_mutex )
  File "/softwares/FINDER/Finder/finder", line 160, in validateCommandLineArguments
    options.verbose = int( options.verbose ) if int( options.verbose ) <= 3 else 3
ValueError: invalid literal for int() with base 10: 'ERROR'

at the command line i provided additional nonmandatory parameters:

run_finder  --metadatafile $PWD/ev-mRNA-metadata_1006_1PM.csv               --output_directory $PWD/output_1006         --genome $PWD/mm10.star/star-indices/mm10.fa           --organism_model VERT           --genemark_path $PWD/gmes_linux_64_4            --genemark_license $PWD/gmes_linux_64_4/LICENSE         --cpu 118               --genome_dir_star $PWD/mm10.star/star.indices/               --genome_dir_olego $PWD/mm10.bwa/         --verbose ERROR         --protein $PWD/mm10.star/uniprotkb_proteome_UP000000589_2023_10_06.fasta               --framework singularity

The Error seems standard and looks like in the code; i believe the problem is on "our side"...

Any ideas? We will greatly appreciate your help.

Have a nice weekend.

--
Iliya Lefterov, MD, PhD
Professor, University of Pittsburgh

***@***.***
***@***.***

412 383 6906 <http://voice.google.com/calls?a=nc,%2B14123836906> - office
412 576 9923 <http://voice.google.com/calls?a=nc,%2B14125769923> - mobile
412 449 9195 <http://voice.google.com/calls?a=nc,%2B14124499195> - mobile
________________________________

**Comment by sagnikbanerjee15** [comment]
Hi @lefterov,

Could you please rerun it without the `--verbose` option?

Thank you.

**Comment by lefterov** [comment]
Singularity without --verbose didn't work either.
We moved to the docker container; at the command line:

run_finder  --metadatafile $PWD/meta/ev-mRNA-metadata_1012.csv \
              --output_directory $PWD/output_1006 \
	      --genome $PWD/mm10.star/star-indices/mm10.fa \
	      --organism_model VERT \
	      --genemark_path $PWD/gmes_linux_64_4 \
	      --genemark_license $PWD/gmes_linux_64_4/LICENSE\
	      --cpu 118 \
	      --genome_dir_star $PWD/mm10.star/star.indices/ \
              --genome_dir_olego $PWD/mm10.bwa/ \
	      --protein $PWD/mm10.star/uniprotkb_proteome_UP000000589_2023_10_06.fasta \
	      --framework docker

 we get this error:

1.1.0: Pulling from sagnikbanerjee15/finder
Digest: sha256:9816d258d2421d4625983c929f508b1f577cfe7ab3bc2042e841647a186c7931
Status: Image is up to date for sagnikbanerjee15/finder:1.1.0
docker.io/sagnikbanerjee15/finder:1.1.0
done
Traceback (most recent call last):
  File "/softwares/FINDER/Finder/finder", line 688, in <module>
    main()
  File "/softwares/FINDER/Finder/finder", line 637, in main
    readMetaDataFile( options, logger_proxy, logging_mutex )
  File "/softwares/FINDER/Finder/scripts/fileReadWriteOperations.py", line 113, in readMetaDataFile
    fhr = open( options.metadatafile, "r" )
FileNotFoundError: [Errno 2] No such file or directory: '/home/iliya/Projects-2023/example_mouse-0918/mRNAseq/meta/ev-mRNA-metadata_1012.csv'
(finder) [iliya@EOH-LEFTEROV2 mRNAseq]$ 

**** The file is there; however no matter it is $PWD, or in a subdirectory (the code above) I get the same error.

it is very possible that the problem is "us"... but where exactly?

Thanks for your time and help.

**Comment by Maxim-Karpov** [comment]
@lefterov 
This issue could be due to the formatting of your metadata file or your reads. Have your paired-end(?) reads been split beforehand? e.g. from reads.fastq to reads_1.fastq + reads_2.fastq (using SRA toolkit's fastq-dump).
