### ISSUE TITLE
 Wrong XA format and combined/psiclass_output_vote.gtf': No such file or directory

### ISSUE THREAD

**Issue by Dalhte** [sagnikbanerjee15/Finder#82]
Hello there
Thanks for having developed this tool
I'm having the same problem as many but I cannot solve it (I already put this message at the end of an old thread but I don't know if you have seen it, I completed my problem analysis a bit more here).
I'm running :
(base) david@Dalhte:/media/david/E/finder_v1.1.0$ run_finder --metadatafile $PWD/Rattus_metadata5.csv --output_directory $PWD/FINDER_test_Rattus --genome $PWD/Rattus_norvegicus.mRatBN7.2.dna.toplevel.fa --organism_model VERT --genemark_path $PWD/gmes_linux_64 --genemark_license $PWD/gm_key_64 --cpu 5 --genome_dir_star $PWD/RN7Genome

Star genom was run independently before and works for other pipelines such as cellranger-arc

and get :
1.1.0: Pulling from sagnikbanerjee15/finder
Digest: sha256:9816d258d2421d4625983c929f508b1f577cfe7ab3bc2042e841647a186c7931
Status: Image is up to date for sagnikbanerjee15/finder:1.1.0
docker.io/sagnikbanerjee15/finder:1.1.0
done
**Error: input 2 3153: Wrong XA format.
mv: cannot stat '/media/david/E/finder_v1.1.0/FINDER_test_Rattus/assemblies_psiclass_modified/combined/psiclass_output_vote.gtf': No such file or directory
Traceback (most recent call last):**
File "/softwares/FINDER/Finder/finder", line 688, in
main()
File "/softwares/FINDER/Finder/finder", line 649, in main
orchestrateGeneModelPrediction( options, logger_proxy, logging_mutex )
File "/softwares/FINDER/Finder/finder", line 461, in orchestrateGeneModelPrediction
findTranscriptsInEachSampleNotReportedInCombinedAnnotations( options, logger_proxy, logging_mutex )
File "/softwares/FINDER/Finder/scripts/findTranscriptsInEachSampleNotReportedInCombinedAnnotations.py", line 17, in findTranscriptsInEachSampleNotReportedInCombinedAnnotations
combined_transcript_info = readAllTranscriptsFromGTFFileInParallel( [combined_gtf_filename, "combined", "combined"] )[0]
File "/softwares/FINDER/Finder/scripts/fileReadWriteOperations.py", line 290, in readAllTranscriptsFromGTFFileInParallel
fhr = open( gtf_filename, "r" )
FileNotFoundError: [Errno 2] No such file or directory: '/media/david/E/finder_v1.1.0/FINDER_test_Rattus/assemblies_psiclass_modified/combined/combined.gtf'

I attached the progress.log and the metafile (I used only one RNA-seq so far just for trial but I do have more)

Here are the error/log for oLego
the indices_olego_index.error : 
[bwa_index] Pack FASTA... 21.42 sec
[bwa_index] Reverse the packed sequence... 7.12 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 1737.93 seconds elapse.
[bwa_index] Construct BWT for the reverse packed sequence...
[bwa_index] 1823.99 seconds elapse.
[bwa_index] Update BWT... 7.24 sec
[bwa_index] Update reverse BWT... 7.57 sec
[bwa_index] Construct SA from BWT and Occ... 463.13 sec
[bwa_index] Construct SA from reverse BWT and Occ... 458.19 sec

the indices_olego_index.output
[BWTIncConstructFromPacked] 10 iterations done. 100000000 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 200000000 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 300000000 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 400000000 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 500000000 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 600000000 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 700000000 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 800000000 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 900000000 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 1000000000 characters processed.
[BWTIncConstructFromPacked] 110 iterations done. 1100000000 characters processed.
[BWTIncConstructFromPacked] 120 iterations done. 1200000000 characters processed.
[BWTIncConstructFromPacked] 130 iterations done. 1300000000 characters processed.
[BWTIncConstructFromPacked] 140 iterations done. 1400000000 characters processed.
[BWTIncConstructFromPacked] 150 iterations done. 1500000000 characters processed.
[BWTIncConstructFromPacked] 160 iterations done. 1600000000 characters processed.
[BWTIncConstructFromPacked] 170 iterations done. 1700000000 characters processed.
[BWTIncConstructFromPacked] 180 iterations done. 1800000000 characters processed.
[BWTIncConstructFromPacked] 190 iterations done. 1900000000 characters processed.
[BWTIncConstructFromPacked] 200 iterations done. 2000000000 characters processed.
[BWTIncConstructFromPacked] 210 iterations done. 2100000000 characters processed.
[BWTIncConstructFromPacked] 220 iterations done. 2200000000 characters processed.
[BWTIncConstructFromPacked] 230 iterations done. 2300000000 characters processed.
[BWTIncConstructFromPacked] 240 iterations done. 2400000000 characters processed.
[BWTIncConstructFromPacked] 250 iterations done. 2500000000 characters processed.
[BWTIncConstructFromPacked] 260 iterations done. 2592871792 characters processed.
[bwt_gen] Finished constructing BWT in 268 iterations.
[BWTIncConstructFromPacked] 10 iterations done. 100000000 characters processed.
[BWTIncConstructFromPacked] 20 iterations done. 200000000 characters processed.
[BWTIncConstructFromPacked] 30 iterations done. 300000000 characters processed.
[BWTIncConstructFromPacked] 40 iterations done. 400000000 characters processed.
[BWTIncConstructFromPacked] 50 iterations done. 500000000 characters processed.
[BWTIncConstructFromPacked] 60 iterations done. 600000000 characters processed.
[BWTIncConstructFromPacked] 70 iterations done. 700000000 characters processed.
[BWTIncConstructFromPacked] 80 iterations done. 800000000 characters processed.
[BWTIncConstructFromPacked] 90 iterations done. 900000000 characters processed.
[BWTIncConstructFromPacked] 100 iterations done. 1000000000 characters processed.
[BWTIncConstructFromPacked] 110 iterations done. 1100000000 characters processed.
[BWTIncConstructFromPacked] 120 iterations done. 1200000000 characters processed.
[BWTIncConstructFromPacked] 130 iterations done. 1300000000 characters processed.
[BWTIncConstructFromPacked] 140 iterations done. 1400000000 characters processed.
[BWTIncConstructFromPacked] 150 iterations done. 1500000000 characters processed.
[BWTIncConstructFromPacked] 160 iterations done. 1600000000 characters processed.
[BWTIncConstructFromPacked] 170 iterations done. 1700000000 characters processed.
[BWTIncConstructFromPacked] 180 iterations done. 1800000000 characters processed.
[BWTIncConstructFromPacked] 190 iterations done. 1900000000 characters processed.
[BWTIncConstructFromPacked] 200 iterations done. 2000000000 characters processed.
[BWTIncConstructFromPacked] 210 iterations done. 2100000000 characters processed.
[BWTIncConstructFromPacked] 220 iterations done. 2200000000 characters processed.
[BWTIncConstructFromPacked] 230 iterations done. 2300000000 characters processed.
[BWTIncConstructFromPacked] 240 iterations done. 2400000000 characters processed.
[BWTIncConstructFromPacked] 250 iterations done. 2500000000 characters processed.
[BWTIncConstructFromPacked] 260 iterations done. 2592871792 characters processed.
[bwt_gen] Finished constructing BWT in 268 iterations.

In the alignemnts file there is the exons.bed and the sorted.out.bam (both look good on IGV)
there is also the _for_psiclass.bam that seems ok too (I indexed it pass it on IGV too)

Can you help ?
Best
David
[progress.log](https://github.com/sagnikbanerjee15/Finder/files/13580711/progress.log)
[Rattus_metadata5.csv](https://github.com/sagnikbanerjee15/Finder/files/13580994/Rattus_metadata5.csv)

**Comment by Gequris** [comment]
> Hello there Thanks for having developed this tool I'm having the same problem as many but I cannot solve it (I already put this message at the end of an old thread but I don't know if you have seen it, I completed my problem analysis a bit more here). I'm running : (base) david@Dalhte:/media/david/E/finder_v1.1.0$ run_finder --metadatafile $PWD/Rattus_metadata5.csv --output_directory $PWD/FINDER_test_Rattus --genome $PWD/Rattus_norvegicus.mRatBN7.2.dna.toplevel.fa --organism_model VERT --genemark_path $PWD/gmes_linux_64 --genemark_license $PWD/gm_key_64 --cpu 5 --genome_dir_star $PWD/RN7Genome
> 
> Star genom was run independently before and works for other pipelines such as cellranger-arc
> 
> and get : 1.1.0: Pulling from sagnikbanerjee15/finder Digest: sha256:9816d258d2421d4625983c929f508b1f577cfe7ab3bc2042e841647a186c7931 Status: Image is up to date for sagnikbanerjee15/finder:1.1.0 docker.io/sagnikbanerjee15/finder:1.1.0 done **Error: input 2 3153: Wrong XA format. mv: cannot stat '/media/david/E/finder_v1.1.0/FINDER_test_Rattus/assemblies_psiclass_modified/combined/psiclass_output_vote.gtf': No such file or directory Traceback (most recent call last):** File "/softwares/FINDER/Finder/finder", line 688, in main() File "/softwares/FINDER/Finder/finder", line 649, in main orchestrateGeneModelPrediction( options, logger_proxy, logging_mutex ) File "/softwares/FINDER/Finder/finder", line 461, in orchestrateGeneModelPrediction findTranscriptsInEachSampleNotReportedInCombinedAnnotations( options, logger_proxy, logging_mutex ) File "/softwares/FINDER/Finder/scripts/findTranscriptsInEachSampleNotReportedInCombinedAnnotations.py", line 17, in findTranscriptsInEachSampleNotReportedInCombinedAnnotations combined_transcript_info = readAllTranscriptsFromGTFFileInParallel( [combined_gtf_filename, "combined", "combined"] )[0] File "/softwares/FINDER/Finder/scripts/fileReadWriteOperations.py", line 290, in readAllTranscriptsFromGTFFileInParallel fhr = open( gtf_filename, "r" ) FileNotFoundError: [Errno 2] No such file or directory: '/media/david/E/finder_v1.1.0/FINDER_test_Rattus/assemblies_psiclass_modified/combined/combined.gtf'
> 
> I attached the progress.log and the metafile (I used only one RNA-seq so far just for trial but I do have more)
> 
> Here are the error/log for oLego the indices_olego_index.error : [bwa_index] Pack FASTA... 21.42 sec [bwa_index] Reverse the packed sequence... 7.12 sec [bwa_index] Construct BWT for the packed sequence... [bwa_index] 1737.93 seconds elapse. [bwa_index] Construct BWT for the reverse packed sequence... [bwa_index] 1823.99 seconds elapse. [bwa_index] Update BWT... 7.24 sec [bwa_index] Update reverse BWT... 7.57 sec [bwa_index] Construct SA from BWT and Occ... 463.13 sec [bwa_index] Construct SA from reverse BWT and Occ... 458.19 sec
> 
> the indices_olego_index.output [BWTIncConstructFromPacked] 10 iterations done. 100000000 characters processed. [BWTIncConstructFromPacked] 20 iterations done. 200000000 characters processed. [BWTIncConstructFromPacked] 30 iterations done. 300000000 characters processed. [BWTIncConstructFromPacked] 40 iterations done. 400000000 characters processed. [BWTIncConstructFromPacked] 50 iterations done. 500000000 characters processed. [BWTIncConstructFromPacked] 60 iterations done. 600000000 characters processed. [BWTIncConstructFromPacked] 70 iterations done. 700000000 characters processed. [BWTIncConstructFromPacked] 80 iterations done. 800000000 characters processed. [BWTIncConstructFromPacked] 90 iterations done. 900000000 characters processed. [BWTIncConstructFromPacked] 100 iterations done. 1000000000 characters processed. [BWTIncConstructFromPacked] 110 iterations done. 1100000000 characters processed. [BWTIncConstructFromPacked] 120 iterations done. 1200000000 characters processed. [BWTIncConstructFromPacked] 130 iterations done. 1300000000 characters processed. [BWTIncConstructFromPacked] 140 iterations done. 1400000000 characters processed. [BWTIncConstructFromPacked] 150 iterations done. 1500000000 characters processed. [BWTIncConstructFromPacked] 160 iterations done. 1600000000 characters processed. [BWTIncConstructFromPacked] 170 iterations done. 1700000000 characters processed. [BWTIncConstructFromPacked] 180 iterations done. 1800000000 characters processed. [BWTIncConstructFromPacked] 190 iterations done. 1900000000 characters processed. [BWTIncConstructFromPacked] 200 iterations done. 2000000000 characters processed. [BWTIncConstructFromPacked] 210 iterations done. 2100000000 characters processed. [BWTIncConstructFromPacked] 220 iterations done. 2200000000 characters processed. [BWTIncConstructFromPacked] 230 iterations done. 2300000000 characters processed. [BWTIncConstructFromPacked] 240 iterations done. 2400000000 characters processed. [BWTIncConstructFromPacked] 250 iterations done. 2500000000 characters processed. [BWTIncConstructFromPacked] 260 iterations done. 2592871792 characters processed. [bwt_gen] Finished constructing BWT in 268 iterations. [BWTIncConstructFromPacked] 10 iterations done. 100000000 characters processed. [BWTIncConstructFromPacked] 20 iterations done. 200000000 characters processed. [BWTIncConstructFromPacked] 30 iterations done. 300000000 characters processed. [BWTIncConstructFromPacked] 40 iterations done. 400000000 characters processed. [BWTIncConstructFromPacked] 50 iterations done. 500000000 characters processed. [BWTIncConstructFromPacked] 60 iterations done. 600000000 characters processed. [BWTIncConstructFromPacked] 70 iterations done. 700000000 characters processed. [BWTIncConstructFromPacked] 80 iterations done. 800000000 characters processed. [BWTIncConstructFromPacked] 90 iterations done. 900000000 characters processed. [BWTIncConstructFromPacked] 100 iterations done. 1000000000 characters processed. [BWTIncConstructFromPacked] 110 iterations done. 1100000000 characters processed. [BWTIncConstructFromPacked] 120 iterations done. 1200000000 characters processed. [BWTIncConstructFromPacked] 130 iterations done. 1300000000 characters processed. [BWTIncConstructFromPacked] 140 iterations done. 1400000000 characters processed. [BWTIncConstructFromPacked] 150 iterations done. 1500000000 characters processed. [BWTIncConstructFromPacked] 160 iterations done. 1600000000 characters processed. [BWTIncConstructFromPacked] 170 iterations done. 1700000000 characters processed. [BWTIncConstructFromPacked] 180 iterations done. 1800000000 characters processed. [BWTIncConstructFromPacked] 190 iterations done. 1900000000 characters processed. [BWTIncConstructFromPacked] 200 iterations done. 2000000000 characters processed. [BWTIncConstructFromPacked] 210 iterations done. 2100000000 characters processed. [BWTIncConstructFromPacked] 220 iterations done. 2200000000 characters processed. [BWTIncConstructFromPacked] 230 iterations done. 2300000000 characters processed. [BWTIncConstructFromPacked] 240 iterations done. 2400000000 characters processed. [BWTIncConstructFromPacked] 250 iterations done. 2500000000 characters processed. [BWTIncConstructFromPacked] 260 iterations done. 2592871792 characters processed. [bwt_gen] Finished constructing BWT in 268 iterations.
> 
> In the alignemnts file there is the exons.bed and the sorted.out.bam (both look good on IGV) there is also the _for_psiclass.bam that seems ok too (I indexed it pass it on IGV too)
> 
> Can you help ? Best David [progress.log](https://github.com/sagnikbanerjee15/Finder/files/13580711/progress.log) [Rattus_metadata5.csv](https://github.com/sagnikbanerjee15/Finder/files/13580994/Rattus_metadata5.csv)

I have exactly the same issue
Here are my files from my run
[Finder_reports.zip](https://github.com/sagnikbanerjee15/Finder/files/13929834/Finder_reports.zip)
Hope somebody could help :(
